name: e_commerce
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
  fonts:
    - family:
      fonts:
        - asset: assets/font
          weight: 400
        - asset: assets/font
          weight: 500
        - asset: assets/font
          weight: 700
        - asset: assets/font
          weight: 900